complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - Preview

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
